/* Pinpoint · AGLC4 source-type definitions.
   Each entry: id, cat, name, rule, k (kind), sec (bibliography section A–E),
   f (fields), ex (example data), cite(d) → HTML string.  Depends on core.js. */
"use strict";
/* ================= SOURCE TYPES ================= */
const CATS=[['cases','Cases & Tribunals','Ch 2'],['leg','Legislation','Ch 3'],['parl','Parliament & Government','Ch 7'],['sec','Journals & Books','Ch 5–6'],['papers','Reports & Papers','Ch 7'],['ref','Reference Works','Ch 7'],['media','Media & Online','Ch 7'],['intl','International','Ch 8–14'],['foreign','Foreign Jurisdictions','Ch 15–25']];
const TYPES=[
/* ---------------- CASES ---------------- */
{id:'case-rep',cat:'cases',name:'Reported case',rule:'2.2',k:'case',sec:'B',
 tip:'Cite the authorised report series where one exists (r 2.2.2). Individuals appear by surname only, and only the first party on each side is named.',
 f:[T('name','Case name',{w:2,req:1,clean:'case',ph:'Orbital Freight Pty Ltd v Commonwealth'}),YB,T('year','Year',{req:1,ph:'2023'}),T('vol','Volume',{ph:'97',help:'Leave blank for series such as [1932] AC.'}),T('rep','Report series',{req:1,list:'dl-series',ph:'ALJR'}),T('page','Starting page',{req:1,ph:'811'}),PIN('824 [41]','Page, then [paragraph] where the report has paragraph numbers.'),T('jj','Judicial officer(s)',{pin:1,ph:'Hartley CJ, Oduya and Venn JJ'}),T('court','Court (only if not apparent)',{w:2,ph:'Supreme Court of New Zealand',help:'r 2.2.6: add only when the report series does not make the court clear.'})],
 ex:{name:'Orbital Freight Pty Ltd v Commonwealth',yb:'round',year:'2023',vol:'97',rep:'ALJR',page:'811',pin:'824 [41]',jj:'Hartley CJ, Oduya and Venn JJ',st:'Orbital Freight'},
 cite:caseRep},
{id:'case-mnc',cat:'cases',name:'Unreported · medium neutral',rule:'2.3.1',k:'case',sec:'B',
 tip:'Use when the court itself allocated the judgment number. Pinpoints are to paragraphs in square brackets. If the case has since been reported, cite the report instead.',
 f:[T('name','Case name',{w:2,req:1,clean:'case',ph:'Re Nexus Robotics Ltd [No 2]'}),T('year','Year',{req:1,ph:'2024'}),T('court','Court identifier',{req:1,list:'dl-mnc',ph:'VSC'}),T('num','Judgment number',{req:1,ph:'318'}),PIN('[57]–[59]','Typing 57-59 becomes [57]–[59].',{para:1}),T('jj','Judicial officer(s)',{pin:1,ph:'Marlowe J'})],
 ex:{name:'Re Nexus Robotics Ltd (No 2)',year:'2024',court:'VSC',num:'318',pin:'57-59',jj:'Marlowe J',st:'Nexus Robotics [No 2]'},
 cite:caseMnc},
{id:'case-unrep',cat:'cases',name:'Unreported · no neutral citation',rule:'2.3.2',k:'case',sec:'B',
 tip:'For older judgments with no court-allocated number. Pinpoints go to the page of the judgment as delivered, with no comma after the date.',
 f:[T('name','Case name',{w:2,req:1,clean:'case',ph:'Carver v Tidewater Shipping Co'}),T('court','Court',{req:1,w:2,ph:'Supreme Court of Tasmania'}),T('jj','Judicial officer(s)',{req:1,ph:'Ashdown J'}),DATE('date','Full date',{req:1}),PIN('12–13')],
 ex:{name:'Carver v Tidewater Shipping Co',court:'Supreme Court of Tasmania',jj:'Ashdown J',date:'14/03/1994',pin:'12-13'},
 cite:d=>`${I(d.name)} (${J(d.court,d.jj,d.date)})`+(d.pin?' '+d.pin:'')},
{id:'case-proc',cat:'cases',name:'Proceeding (no judgment yet)',rule:'2.3.3',k:'case',sec:'B',
 tip:'For a matter that has been filed but has no judgment or order yet, or that was discontinued. Write the proceeding number without spaces.',
 f:[T('name','Case name',{w:2,req:1,clean:'case',ph:'Data Commissioner v Lumen Drones Pty Ltd'}),T('court','Court',{req:1,w:2,ph:'Federal Court of Australia'}),T('num','Proceeding number',{req:1,ph:'VID512/2025'}),DATE('date','Date commenced',{req:1})],
 ex:{name:'Data Commissioner v Lumen Drones Pty Ltd',court:'Federal Court of Australia',num:'VID512/2025',date:'3 February 2025'},
 cite:d=>`${I(d.name)} (${J(d.court,d.num.replace(/\s+/g,''),'commenced '+d.date)})`},
{id:'case-order',cat:'cases',name:'Court order',rule:'2.3.4',k:'case',sec:'B',
 tip:'Only for an order that is not contained in a judgment. Include a proceeding number only if it appears on the order.',
 f:[T('jj','Judicial officer(s)',{req:1,ph:'Kestrel J'}),T('name','Case name',{req:1,clean:'case',ph:'Halden v Skyward Networks Pty Ltd'}),T('court','Court',{req:1,ph:'Federal Court of Australia'}),T('num','Proceeding number',{ph:'NSD1044/2024'}),DATE('date','Date of order',{req:1})],
 ex:{jj:'Kestrel J',name:'Halden v Skyward Networks Pty Ltd',court:'Federal Court of Australia',num:'NSD1044/2024',date:'9 October 2024'},
 cite:d=>`Order of ${d.jj} in ${I(d.name)} (${J(d.court,d.num,d.date)})`, sort:d=>d.name, txt:d=>({first:`the order of ${d.jj} in ${I(d.name)}`,later:I(d.st||d.name)})},
{id:'tribunal',cat:'cases',name:'Tribunal / administrative decision',rule:'2.6.1',k:'case',sec:'B',
 tip:'Cited like a case. Keep “and” where the decision uses it instead of “v”. Titles such as “Member”, “Senior Member” or “Dr” go before a decision-maker’s name.',
 f:[S('mode','Citation form',[['mnc','Medium neutral, eg [2023] AATA 1177'],['rep','Reported, eg (1979) 26 ALD 247']],{w:2}),T('name','Decision name',{w:2,req:1,clean:'case',ph:'Quill and Secretary, Department of Future Industries'}),
   {...YB,when:d=>d.mode==='rep'},T('year','Year',{req:1}),T('vol','Volume',{when:d=>d.mode==='rep'}),T('rep','Report series',{list:'dl-series',when:d=>d.mode==='rep',req:1}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),
   T('court','Tribunal identifier',{when:d=>d.mode==='mnc',req:1,list:'dl-mnc',ph:'AATA'}),T('num','Decision number',{when:d=>d.mode==='mnc',req:1}),PIN('[42]','',{para:d=>d.mode==='mnc'}),T('jj','Member(s)',{pin:1,ph:'Senior Member Ravel'})],
 ex:{mode:'mnc',yb:'round',name:'Quill and Secretary, Department of Future Industries',year:'2023',court:'AATA',num:'1177',pin:'42',jj:'Senior Member Ravel',st:'Quill'},
 cite:d=>d.mode==='rep'?caseRep(d):caseMnc(d)},
{id:'arbitration',cat:'cases',name:'Arbitral award',rule:'2.6.2',k:'case',sec:'B',
 tip:'Include only what appears on the award. If no party names appear, the remaining elements are not put in parentheses. Use the “reported in” field when the award is reproduced in a report, book or journal.',
 f:[T('name','Party names (if shown)',{w:2,clean:'case',ph:'Aurora Satellite Systems Inc v Veloria'}),T('desc','Award description',{req:1,ph:'Final Award'}),T('forum','Forum or arbitrator(s)',{req:1,ph:'International Chamber of Commerce'}),T('caseno','Case / award number',{ph:'Case No 24417/MK'}),DATE('date','Full date',{req:1}),T('rep','Reported in (optional)',{w:2,ph:'(2023) 62 ILM 1140',help:'A full citation to the reproduction, including its starting page.'}),PIN('[112]','If reported, pinpoint to the reproduction.')],
 ex:{name:'Aurora Satellite Systems Inc v Veloria',desc:'Final Award',forum:'International Chamber of Commerce',caseno:'Case No 24417/MK',date:'18 May 2022',pin:'[112]'},
 cite:d=>{const inner=J(d.desc,d.forum,d.caseno,d.date);let s=d.name?`${I(d.name)} (${inner})`:inner;if(d.rep)s+=` reported in ${d.rep}`+(d.pin?', '+d.pin:'');else if(d.pin)s+=(d.name?' ':', ')+d.pin;return s;},
 sort:d=>d.name||d.desc, txt:d=>({first:d.name?I(d.name):`the ${d.desc}`,later:d.st?I(d.st):I(d.name)})},
{id:'transcript',cat:'cases',name:'Transcript of proceedings',rule:'2.7',k:'case',sec:'E',
 tip:'High Court transcripts from July 2003 carry an HCATrans number and pinpoint to line numbers. A speaker may follow the pinpoint, but not “(during argument)”.',
 f:[S('mode','Transcript type',[['gen','General (any court)'],['hca','High Court · HCATrans']],{w:2}),T('name','Case name',{w:2,req:1,clean:'case',ph:'Vantablack Holdings Ltd v Commissioner of Taxation'}),
   T('court','Court',{req:1,when:d=>d.mode==='gen',ph:'Supreme Court of Victoria'}),T('num','Proceeding number',{when:d=>d.mode==='gen',help:'Only if it appears on the transcript.'}),T('jj','Judicial officer(s)',{req:1,when:d=>d.mode==='gen'}),DATE('date','Date of proceedings',{req:1,when:d=>d.mode==='gen'}),
   T('year','Year',{req:1,when:d=>d.mode==='hca'}),T('hnum','HCATrans number',{req:1,when:d=>d.mode==='hca'}),PIN('1420–35','Page or line numbers'),T('spk','Speaker',{pin:1,ph:'Hartley CJ'})],
 ex:{mode:'hca',name:'Vantablack Holdings Ltd v Commissioner of Taxation',year:'2024',hnum:'61',pin:'1420-35',spk:'Hartley CJ'},
 cite:d=>{const sp=d.pin&&d.spk?` (${d.spk})`:'';if(d.mode==='hca')return `Transcript of Proceedings, ${I(d.name)} [${d.year}] HCATrans ${d.hnum}`+(d.pin?', '+d.pin:'')+sp;return `Transcript of Proceedings, ${I(d.name)} (${J(d.court,d.num,d.jj,d.date)})`+(d.pin?' '+d.pin:'')+sp;},
 txt:d=>({first:`the transcript of proceedings in ${I(d.name)}`,later:I(d.st||d.name)})},
{id:'case-sub',cat:'cases',name:'Submissions in a case',rule:'2.8',k:'other',sec:'E',ts:'q',tf:'title',
 tip:'The party’s name appears in full. Include the submission title and proceeding number only if they appear on the document.',
 f:[T('party','Party / author',{w:2,req:1,ph:'Attorney-General (Cth)'}),T('title','Title of submission',{w:2,title:1}),T('name','Case name',{w:2,req:1,clean:'case'}),T('num','Proceeding number'),DATE('date','Date of submission',{req:1}),PIN('[18]–[22]')],
 ex:{party:'Attorney-General (Cth)',title:'Outline of submissions of the Attorney-General as intervener',name:'Orbital Freight Pty Ltd v Commonwealth',num:'M14/2023',date:'2 June 2023',pin:'[18]-[22]'},
 cite:d=>J(d.party,Q(d.title),'Submission in '+I(d.name),d.num,d.date,d.pin), subHead:d=>d.st?Q(d.st):`${d.party}, ${Q(d.title)}`},

/* ---------------- LEGISLATION ---------------- */
{id:'act',cat:'leg',name:'Act of Parliament',rule:'3.1',k:'leg',sec:'C',
 tip:'Use the short title in italics, the year, and the abbreviated jurisdiction. State constitutions are cited as ordinary Acts, and so are New Zealand statutes, with (NZ).',
 f:LEGF('Autonomous Vehicles (Safety and Liability) Act','2024','s 12(3)(b)'),
 ex:{title:'Autonomous Vehicles (Safety and Liability) Act',year:'2024',jur:'Vic',pin:'s 12(3)(b)',st:'AV Act'},
 cite:d=>actCite(d)},
{id:'bill',cat:'leg',name:'Bill',rule:'3.2',k:'leg',sec:'C',ni:1,
 tip:'Bills are cited like Acts, except that the title and year are not italicised. Pinpoints are usually to clauses (cl) and sub-clauses.',
 f:LEGF('Online Safety Amendment (Synthetic Media) Bill','2025','cl 7(2)'),
 ex:{title:'Online Safety Amendment (Synthetic Media) Bill',year:'2025',jur:'Cth',pin:'sch 1 item 4'},
 cite:d=>actCite(d,false)},
{id:'deleg',cat:'leg',name:'Delegated legislation',rule:'3.4',k:'leg',sec:'C',
 tip:'Regulations, rules and orders are cited like Acts. Extra pinpoint abbreviations: reg / regs, r / rr, ord / ords, sub-reg, sub-r.',
 f:LEGF('Drone Operations Regulations','2022','reg 14(2)'),
 ex:{title:'Drone Operations Regulations',year:'2022',jur:'NSW',pin:'reg 14(2)'},
 cite:d=>actCite(d)},
{id:'const',cat:'leg',name:'Australian Constitution',rule:'3.6',k:'leg',sec:'C',st:false,
 tip:'The Commonwealth Constitution can be cited as the Australian Constitution. Cite it within its Imperial enacting Act only where that is necessary. State constitutions are cited as ordinary Acts.',
 f:[S('mode','Form',[['aust','Australian Constitution'],['imp','Within the Imperial enacting Act']],{w:2}),PIN('s 51(xxxi)','',{nodash:1,w:2})],
 ex:{mode:'aust',pin:'s 51(xxxi)'},
 cite:d=>d.mode==='imp'?`${I('Commonwealth of Australia Constitution Act 1900')} (Imp) 63 &amp; 64 Vict, c 12`+(d.pin?', '+d.pin:''):SP(I('Australian Constitution'),d.pin),
 txt:d=>({first:d.mode==='imp'?I('Commonwealth of Australia Constitution Act 1900')+' (Imp)':'the '+I('Australian Constitution'),later:'the '+I('Constitution')}),
 subHead:d=>I(d.mode==='imp'?'Commonwealth of Australia Constitution Act 1900':'Australian Constitution')},
{id:'em',cat:'leg',name:'Explanatory memorandum',rule:'3.7',k:'other',sec:'E',st:true,
 tip:'Also covers explanatory statements and notes. The Bill is cited as in r 3.2. Second reading speeches are Hansard, so use the Parliamentary debates type for those.',
 f:[S('kind','Document',[['Explanatory Memorandum','Explanatory Memorandum'],['Revised Explanatory Memorandum','Revised Explanatory Memorandum'],['Supplementary Explanatory Memorandum','Supplementary Explanatory Memorandum'],['Explanatory Statement','Explanatory Statement'],['Explanatory Notes','Explanatory Notes']],{w:2}),T('title','Bill title (without year)',{w:2,req:1}),T('year','Year',{req:1}),T('jur','Jurisdiction',{req:1,list:'dl-jur'}),PIN('7 [23]','Page, or page and [paragraph].',{w:2})],
 ex:{kind:'Explanatory Memorandum',title:'Online Safety Amendment (Synthetic Media) Bill',year:'2025',jur:'Cth',pin:'7 [23]'},
 cite:d=>`${d.kind}, ${SP(d.title,d.year)} (${d.jur})`+(d.pin?' '+d.pin:''),
 txt:d=>({first:`the ${d.kind} to the ${SP(d.title,d.year)} (${d.jur})`,later:`the ${d.kind}`}),
 subHead:d=>d.st||`${d.kind}, ${SP(d.title,d.year)} (${d.jur})`},
{id:'leghist',cat:'leg',name:'Legislative history',rule:'3.8',k:'leg',sec:'C',st:false,
 tip:'Links an original provision to the instrument that amended, inserted or repealed it. The linking phrases are not interchangeable, so choose the one that matches what happened.',
 f:[T('t1','Act cited (without year)',{w:2,req:1,ph:'Crimes Act'}),T('y1','Year',{req:1}),T('j1','Jurisdiction',{req:1,list:'dl-jur'}),T('p1','Provision',{w:2,ph:'s 31B',pin:1,nodash:1}),
   S('rel','Relationship',[['as inserted by','as inserted by'],['inserting','inserting'],['as amended by','as amended by'],['later amended by','later amended by'],['amending','amending'],['as repealed by','as repealed by'],['repealing','repealing'],['as enacted','as enacted'],['as at','as at [date]']],{w:2}),
   DATE('date','Date (for “as at”)',{when:d=>d.rel==='as at',w:2}),
   T('t2','Second instrument (without year)',{w:2,when:d=>!['as enacted','as at'].includes(d.rel)}),T('y2','Year',{when:d=>!['as enacted','as at'].includes(d.rel)}),T('j2','Jurisdiction',{list:'dl-jur',when:d=>!['as enacted','as at'].includes(d.rel)}),T('p2','Provision',{w:2,pin:1,nodash:1,when:d=>!['as enacted','as at'].includes(d.rel)}),C('b2','Second instrument is a Bill (not italicised)',{w:2,when:d=>!['as enacted','as at'].includes(d.rel)})],
 ex:{t1:'Crimes Act',y1:'1958',j1:'Vic',p1:'s 31B',rel:'as inserted by',t2:'Crimes Amendment (Critical Infrastructure) Act',y2:'2024',j2:'Vic',p2:'s 6'},
 cite:d=>{const a=SP(I(SP(d.t1,d.y1)),`(${d.j1})`,d.p1);if(d.rel==='as enacted')return a+', as enacted';if(d.rel==='as at')return `${a}, as at ${d.date}`;const t2=SP(d.t2,d.y2);return `${a}, ${d.rel} `+SP(d.b2?t2:I(t2),`(${d.j2})`,d.p2);},
 sort:d=>d.t1, txt:d=>({first:`${I(SP(d.t1,d.y1))} (${d.j1})`,later:I(SP(d.t1,d.y1))}), subHead:d=>`${I(SP(d.t1,d.y1))} (${d.j1})`},
{id:'gazette',cat:'leg',name:'Government gazette',rule:'3.9.1',k:'other',sec:'E',ts:'i',tf:'gtitle',
 tip:'Where several notices share a gazette or page, add the notice’s author and title, plus the starting page.',
 f:[T('author','Notice author (optional)',{ph:'Minister for Lands (WA)'}),T('ntitle','Notice title (optional)',{title:1}),T('jur','Jurisdiction',{req:1,ph:'Commonwealth'}),T('gtitle','Gazette title',{req:1,ph:'Gazette: Special'}),T('num','Gazette number',{req:1,ph:'S 212'}),DATE('date','Full date',{req:1}),T('start','Starting page (with notice)',{when:d=>!!d.ntitle}),PIN('3')],
 ex:{jur:'Commonwealth',gtitle:'Gazette: Special',num:'S 212',date:'4 August 2025',pin:'3'},
 cite:d=>d.ntitle?`${J(d.author,Q(d.ntitle))} in ${J(d.jur,I(d.gtitle),'No '+d.num,d.date,d.start,d.pin)}`:J(d.jur,I(d.gtitle),'No '+d.num,d.date,d.pin),
 subHead:d=>d.st||J(d.jur,I(d.gtitle),'No '+d.num)},
{id:'ruling',cat:'leg',name:'Ruling / class order / direction',rule:'3.9.2',k:'other',sec:'E',ts:'i',
 tip:'For ATO rulings, ASIC class orders, ministerial directions and similar instruments. Give only the officer’s title, not their name. The date is the date the instrument takes effect.',
 f:[T('body','Instrumentality / officer',{w:2,req:1,ph:'Australian Taxation Office'}),T('title','Instrument title',{w:2,req:1,title:1}),T('docno','Document number',{ph:'TR 2024/D3'}),DATE('date','Date of effect',{req:1}),PIN('[14]')],
 ex:{body:'Australian Taxation Office',title:'Income Tax: Deductibility of Orbital Launch Expenses',docno:'TR 2024/D3',date:'1 July 2024',pin:'[14]'},
 cite:d=>`${d.body}, ${I(d.title)} (${J(d.docno,d.date)})`+(d.pin?' '+d.pin:'')},
{id:'nongov',cat:'leg',name:'Rules of non-government bodies',rule:'3.9.3',k:'other',sec:'E',ts:'i',
 tip:'For ASX Listing Rules, professional conduct rules and similar. Leave out “Pty”, “Ltd”, “Inc” and a leading “The” from the body’s name.',
 f:[T('body','Issuing body',{req:1,ph:'ASX'}),T('title','Title',{req:1,title:1,ph:'Listing Rules'}),DATE('date','Version date (at …)',{req:1}),PIN('r 3.1','',{nodash:1})],
 ex:{body:'ASX',title:'Listing Rules',date:'1 December 2024',pin:'r 3.1'},
 cite:d=>`${d.body}, ${I(d.title)} (at ${d.date})`+(d.pin?' '+d.pin:'')},
{id:'practice',cat:'leg',name:'Practice note / direction',rule:'3.9.4',k:'other',sec:'E',ts:'i',
 tip:'Cite the version reproduced in the court’s authorised report series where there is one. Put “No” before the identifier only when it is clearly a number.',
 f:[T('court','Court',{w:2,req:1,ph:'Supreme Court of Victoria'}),T('ident','Identifier',{req:1,ph:'Practice Note SC Gen 21'}),T('title','Title',{req:1,title:1}),S('mode','Published',[['unrep','Not in a report series (use date)'],['rep','Reproduced in a report series']],{w:2}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),T('repc','Report citation',{when:d=>d.mode==='rep',req:1,ph:'(2010) 30 VR 693'}),PIN('[4.1]')],
 ex:{court:'Supreme Court of Victoria',ident:'Practice Note SC Gen 21',title:'Use of Generative Artificial Intelligence in Proceedings',mode:'unrep',date:'6 May 2024',pin:''},
 cite:d=>`${d.court}, ${I(d.ident+': '+d.title)}`+(d.mode==='rep'?' '+d.repc:', '+d.date)+(d.pin?', '+d.pin:''),
 txt:d=>({first:I(d.ident+': '+d.title),later:d.st?I(d.st):I(d.ident)}),subHead:d=>d.st?I(d.st):`${d.court}, ${I(d.ident)}`},

/* ---------------- PARLIAMENT & GOVERNMENT ---------------- */
{id:'hansard',cat:'parl',name:'Parliamentary debates (Hansard)',rule:'7.5.1',k:'other',sec:'E',
 tip:'Also used for second reading speeches. Give the speaker’s first and last names without MP, Senator or “the Hon”. A ministerial position may follow after a comma.',
 f:[T('jur','Jurisdiction',{req:1,ph:'Commonwealth'}),T('chamber','Chamber',{req:1,ph:'House of Representatives'}),DATE('date','Date of debate',{req:1}),PIN('1432'),T('spk','Speaker',{clean:'name',ph:'Mara Ellison'}),T('pos','Position (optional)',{ph:'Minister for Communications'})],
 ex:{jur:'Commonwealth',chamber:'House of Representatives',date:'12 February 2025',pin:'1432',spk:'Mara Ellison',pos:'Minister for Communications'},
 cite:d=>J(d.jur,I('Parliamentary Debates'),d.chamber,d.date,d.pin)+(d.spk?` (${J(d.spk,d.pos)})`:''),
 txt:d=>({first:d.spk?`${d.spk}’s speech to the ${d.chamber} on ${d.date}`:`debate in the ${d.chamber} on ${d.date}`,later:d.spk||'the debate'}),
 subHead:d=>d.st||J(d.jur,I('Parliamentary Debates'),d.chamber,d.date)},
{id:'subinq',cat:'parl',name:'Submission to an inquiry',rule:'7.5.2',k:'other',sec:'E',ts:'i',tf:'inquiry',
 tip:'For a parliamentary committee, the body is “Committee, Legislature”. Leave out the submission number if the body doesn’t allocate one, and the inquiry name for a royal commission.',
 f:[AU('au','Author (leave blank if anonymous)'),T('no','Submission number',{ph:'42'}),T('committee','Committee / body',{w:2,req:1,ph:'Senate Standing Committee on Environment and Communications'}),T('legis','Legislature (for committees)',{w:2,ph:'Parliament of Australia'}),T('inquiry','Name of inquiry',{w:2,title:1}),DATE('date','Date'),PIN('4 [12]')],
 ex:{au:[body('Coastal Futures Alliance')],no:'42',committee:'Senate Standing Committee on Environment and Communications',legis:'Parliament of Australia',inquiry:'Inquiry into Offshore Carbon Storage',date:'19 March 2025',pin:'4 [12]'},
 cite:d=>{const a=authorsText(d.au,d._bib);const s=`${a?'Submission':'Submission'}${d.no?' No '+d.no:''} to ${J(d.committee,d.legis)}`;return J(a,s)+(d.inquiry?`, ${I(d.inquiry)}`:'')+(d.date?` (${d.date})`:'')+(d.pin?' '+d.pin:'');}},
{id:'evidence',cat:'parl',name:'Evidence to a committee',rule:'7.5.3',k:'other',sec:'E',
 tip:'Committee Hansard page numbers often carry a committee prefix such as “SL&C”; leave the prefix out of the pinpoint.',
 f:[T('committee','Committee',{w:2,req:1,ph:'Senate Select Committee on Autonomous Systems'}),T('legis','Legislature',{req:1,ph:'Parliament of Australia'}),T('loc','Location',{req:1,ph:'Canberra'}),DATE('date','Full date',{req:1}),PIN('14'),T('spk','Name of person giving evidence',{req:1,clean:'name'}),T('pos','Position (optional)')],
 ex:{committee:'Senate Select Committee on Autonomous Systems',legis:'Parliament of Australia',loc:'Canberra',date:'2 October 2024',pin:'14',spk:'Tessa Marlow',pos:'Director, Centre for Space Law'},
 cite:d=>'Evidence to '+J(d.committee,d.legis,d.loc,d.date,d.pin)+` (${J(d.spk,d.pos)})`,
 txt:d=>({first:`${d.spk}’s evidence to the ${d.committee}`,later:d.spk}),subHead:d=>d.st||('Evidence to '+J(d.committee,d.legis,d.loc,d.date))},
{id:'convention',cat:'parl',name:'Federal convention debates',rule:'7.5.4',k:'other',sec:'E',ts:'i',
 tip:'For the 1890s Australasian federal conventions. Speakers are named without titles, except Sir, Dame and peerage titles.',
 f:[T('title','Title of record',{w:2,req:1,ph:'Official Record of the Debates of the Australasian Federal Convention'}),T('loc','Location',{req:1,ph:'Melbourne'}),DATE('date','Full date',{req:1}),PIN('672'),T('spk','Speaker',{clean:'name'})],
 ex:{title:'Official Record of the Debates of the Australasian Federal Convention',loc:'Melbourne',date:'8 February 1898',pin:'672',spk:'Edmund Barton'},
 cite:d=>J(I(d.title),d.loc,d.date,d.pin)+(d.spk?` (${d.spk})`:'')},
{id:'rpt-comm',cat:'parl',name:'Parliamentary committee report',rule:'7.1.2',k:'sec',sec:'A',ts:'i',
 tip:'The author is “Committee, Legislature”. Bills digests and alert digests work the same way, using “Digest No 9 of 2025” as the document number.',
 f:[T('committee','Committee',{w:2,req:1,ph:'Senate Select Committee on Autonomous Systems'}),T('legis','Legislature',{w:2,req:1,ph:'Parliament of Australia'}),T('title','Report title',{w:2,req:1,title:1}),...RPT_TAIL()],
 ex:{committee:'Senate Select Committee on Autonomous Systems',legis:'Parliament of Australia',title:'Accountability for algorithmic decision-making',dtype:'Report',date:'November 2024',pin:'57 [3.41]'},
 cite:d=>rptCite(J(d.committee,d.legis),d), subHead:d=>d.st?I(d.st):J(d.committee,d.legis)},
{id:'media',cat:'parl',name:'Press / media release',rule:'7.4',k:'sec',sec:'E',ts:'q',
 tip:'Name both the author and the releasing body. Leave the body out if it is the same as the author. Use “Media Release” if the release type isn’t shown.',
 f:[AU(),T('title','Title',{w:2,req:1,title:1}),T('rtype','Release type',{list:'dl-release',ph:'Media Release'}),T('dno','Document number'),T('body','Releasing body',{w:2,ph:'Minister for Communications'}),DATE('date','Full date',{req:1}),PIN('2')],
 ex:{au:[person('Mara','Ellison')],title:'New safeguards for synthetic media',rtype:'Media Release',body:'Minister for Communications',date:'12 February 2025'},
 cite:d=>J(authorsText(d.au,d._bib),Q(d.title))+` (${J(SP(d.rtype||'Media Release',d.dno),d.body,d.date)})`+(d.pin?' '+d.pin:'')},

/* ---------------- JOURNALS & BOOKS ---------------- */
{id:'journal',cat:'sec',name:'Journal article',rule:'5',k:'sec',sec:'A',ts:'q',
 tip:'Give the journal’s full title in italics without a leading “The”. Use ( ) for journals organised by volume and [ ] for those organised by year. Online-only articles use an article number in place of the starting page.',
 f:[AU(),T('title','Article title',{w:2,req:1,title:1}),T('part','Part (if published in parts)',{ph:'1'}),YB,T('year','Year',{req:1}),T('vol','Volume',{ph:'47'}),T('issue','Issue',{ph:'2',help:'Number, season or month.'}),T('journal','Journal',{w:2,req:1,ph:'University of New Westland Law Review'}),
   S('status','Status',[['pub','Published'],['forthcoming','Forthcoming'],['advance','Advance']]),T('page','Starting page / article no',{req:1,ph:'233',when:d=>d.status==='pub'}),T('range','PDF page range (article numbers only)',{when:d=>d.status==='pub',ph:'1–19',help:'For a PDF article with an article number: 416:1–19, 8.'}),{...PIN('241–3'),when:d=>d.status==='pub'}],
 ex:{au:[person('Priya','Venkataraman'),person('Tomas','Hale')],title:'Salvage rights in low earth orbit: towards a property law of space debris',yb:'round',year:'2024',vol:'47',issue:'2',journal:'University of New Westland Law Review',status:'pub',page:'233',pin:'241-3'},
 cite:d=>{
   if(/^the\s/i.test(pl(d.journal))){d.journal=d.journal.replace(/^the\s+/i,'');d._w.push(['fix','Dropped the leading “The” from the journal title (r 5.5).']);}
   const iss=d.issue?(/^[\d–\-]+$/.test(pl(d.issue))?`(${dash(d.issue)})`:` (${d.issue})`):'';
   const yv=d.yb==='square'?`[${d.year}]`+(d.issue?` (${d.issue})`:''):`(${d.year})`+(d.vol?' '+d.vol+iss:(d.issue?` (${d.issue})`:''));
   const pp=d.status==='forthcoming'?'(forthcoming)':d.status==='advance'?'(advance)':d.page+(d.range?':'+dash(d.range):'')+(d.pin?', '+d.pin:'');
   if(d.yb==='round'&&d.vol&&!d.issue&&!d._bib)d._w.push(['info','Include the issue number where the journal has one, eg 40(3) (r 5.4).']);
   return J(authorsText(d.au,d._bib),Q(d.title))+(d.part?` (Pt ${d.part})`:'')+' '+SP(yv,I(d.journal),pp);}},
{id:'book',cat:'sec',name:'Book',rule:'6',k:'sec',sec:'A',ts:'i',
 tip:'Leave “Pty”, “Ltd”, a leading “The” and geographical words out of the publisher’s name. Give the edition only where the book shows one. Pinpoints follow the publication details without a comma.',
 f:[AU('au','Author(s) or editor(s)'),S('role','These people are',[['au','Authors'],['eds','Editors (no author)']]),T('title','Title',{w:2,req:1,title:1}),T('edby','Edited by (book with author and editor)',{ph:'Roger Crisp',clean:'name'}),T('trby','Translated by',{clean:'name'}),T('pub','Publisher',{req:1,ph:'Meridian Legal Press'}),T('edn','Edition',{ph:'2'}),C('rev','Revised edition (rev ed)'),C('fc','Forthcoming'),T('year','Year',{req:1,when:d=>!d.fc}),S('volk','Volume label',[['vol','vol'],['bk','bk']]),T('vol','Volume',{ph:'2'}),PIN('117 [4.32]','Page, [paragraph], or ch / pt.',{w:2})],
 ex:{au:[person('Imogen','Carrow')],role:'au',title:'Artificial agents and the law of obligations',pub:'Meridian Legal Press',edn:'2',year:'2025',volk:'vol',pin:'117 [4.32]'},
 cite:d=>{
   if(/^the\s/i.test(d.pub)){d.pub=d.pub.replace(/^the\s+/i,'');d._w.push(['fix','Dropped the leading “The” from the publisher (r 6.3.1).']);}
   const o=d.pub;d.pub=d.pub.replace(/\s+(Pty|Ltd|Co|Inc|Limited)\b\.?/g,'');if(o!==d.pub)d._w.push(['fix','Removed corporate-status words from the publisher (r 6.3.1).']);
   const who=authorsText(d.au,d._bib,d.role==='eds');const mid=J(I(d.title),d.edby?'ed '+d.edby:'',d.trby?'tr '+d.trby:'');
   const edn=d.edn?ord(d.edn)+(d.rev?' rev':'')+' ed':'';const pubd=J(d.pub,edn,(!d.edn&&d.rev)?'rev ed':'',d.fc?'forthcoming':d.year);
   let s=`${J(who,mid)} (${pubd})`;if(d.vol)s+=` ${d.volk||'vol'} ${d.vol}`+(d.pin?', '+d.pin:'');else if(d.pin)s+=' '+d.pin;return s;},
 role:d=>d.role==='eds'},
{id:'chapter',cat:'sec',name:'Chapter in edited book',rule:'6.6.1',k:'sec',sec:'A',ts:'q',tf:'ctitle',
 tip:'Later references use the chapter author’s name and point back to the footnote where that chapter was first cited in full.',
 f:[AU('au','Chapter author(s)'),T('ctitle','Chapter title',{w:2,req:1,title:1}),AU('eds','Editor(s) of the book'),T('btitle','Book title',{w:2,req:1,title:1}),T('pub','Publisher',{req:1}),T('edn','Edition'),T('year','Year',{req:1}),T('start','Starting page of chapter',{req:1}),PIN('160–2')],
 ex:{au:[person('Sofia','Marchetti')],ctitle:'Robots, agency and vicarious liability',eds:[person('Imogen','Carrow'),person('Bernard','Osei')],btitle:'Torts in the machine age',pub:'Meridian Legal Press',year:'2024',start:'151',pin:'160-2'},
 cite:d=>`${J(authorsText(d.au,d._bib),Q(d.ctitle))} in ${J(authorsText(d.eds,false,true),I(d.btitle))} (${J(d.pub,d.edn?ord(d.edn)+' ed':'',d.year)}) ${d.start}`+(d.pin?', '+d.pin:'')},
{id:'audiobook',cat:'sec',name:'Audiobook',rule:'6.9',k:'sec',sec:'A',ts:'i',
 tip:'Give the audiobook publisher and year, not those of the print edition. Pinpoint to a time or time span in the recording, eg 1:02:10–1:04:45.',
 f:[AU(),T('title','Title',{w:2,req:1,title:1}),T('pub','Audiobook publisher',{req:1}),T('year','Year',{req:1}),PIN('2:14:05','Time, as h:mm:ss')],
 ex:{au:[person('Imogen','Carrow')],title:'The algorithmic judge',pub:'Lumen Audio',year:'2023',pin:'2:14:05'},
 cite:d=>`${J(authorsText(d.au,d._bib),I(d.title))} (Audiobook, ${J(d.pub,d.year)})`+(d.pin?' '+d.pin:'')},

/* ---------------- REPORTS & PAPERS ---------------- */
{id:'rpt',cat:'papers',name:'Report (general)',rule:'7.1.1',k:'sec',sec:'A',ts:'i',
 tip:'Annual reports, NGO and government reports. If “Annual Report” is part of the title, use the plain type “Report”. Leave the author out where the report doesn’t prominently name one.',
 f:[AU('au','Author (person or body)'),T('title','Title',{w:2,req:1,title:1}),...RPT_TAIL()],
 ex:{au:[body('Institute for Orbital Policy')],title:'Debris, liability and the commons of space',dtype:'Report',date:'March 2023',pin:'14'},
 cite:d=>rptCite(authorsText(d.au,d._bib),d)},
{id:'rpt-royal',cat:'papers',name:'Royal commission report',rule:'7.1.3',k:'sec',sec:'A',ts:'i',
 tip:'Usually no author and never a jurisdiction. Where the report has several volumes, include the volume even if the pages run on across volumes.',
 f:[T('title','Title',{w:2,req:1,title:1,ph:'Royal Commission into …'}),...RPT_TAIL()],
 ex:{title:'Royal Commission into Critical Infrastructure Resilience',dtype:'Final Report',date:'June 2025',vol:'2',pin:'311'},
 cite:d=>rptCite('',d)},
{id:'rpt-lrc',cat:'papers',name:'Law reform commission paper',rule:'7.1.4',k:'sec',sec:'A',ts:'i',
 tip:'Give the type of publication, such as Report, Discussion Paper, Issues Paper or Consultation Paper, as the document type.',
 f:[T('lrc','Commission',{w:2,req:1,list:'dl-lrc',ph:'Tasman Law Reform Commission'}),T('title','Title',{w:2,req:1,title:1}),...RPT_TAIL()],
 ex:{lrc:'Tasman Law Reform Commission',title:'Neural data and privacy',dtype:'Report',dno:'152',date:'May 2025',pin:'88 [5.12]',st:'Neural Data Report'},
 cite:d=>rptCite(d.lrc,d),subHead:d=>d.st?I(d.st):d.lrc},
{id:'rpt-abs',cat:'papers',name:'ABS statistics',rule:'7.1.5',k:'sec',sec:'A',ts:'i',
 tip:'The author is always the Australian Bureau of Statistics, and the document is cited by its catalogue number.',
 f:[T('title','Title',{w:2,req:1}),T('dno','Catalogue number',{req:1,ph:'8172.0'}),DATE('date','Release date'),PIN('16–17')],
 ex:{title:'Household Use of Artificial Intelligence, Australia, 2024–25',dno:'8172.0',date:'14 August 2025',pin:''},
 cite:d=>`Australian Bureau of Statistics, ${I(d.title)} (${J('Catalogue No '+d.dno,d.date)})`+(d.pin?' '+d.pin:''),sort:()=>'Australian Bureau of Statistics',subHead:d=>d.st?I(d.st):'Australian Bureau of Statistics'},
{id:'paper',cat:'papers',name:'Research / working paper',rule:'7.2.2',k:'sec',sec:'A',ts:'q',
 tip:'Copy the paper’s series identifier exactly. For the institution, give the most specific subdivision and then the umbrella body.',
 f:PAPER('Research Paper','Institution','Faculty of Law, University of New Westland'),
 ex:{au:[person('Lena','Okafor')],title:'Consent fatigue and the limits of notice-and-choice privacy',dtype:'Research Paper',dno:'24-07',inst:'Faculty of Law, University of New Westland',date:'July 2024',pin:'9'},
 cite:paperCite},
{id:'paper-parl',cat:'papers',name:'Parliamentary library paper',rule:'7.2.3',k:'sec',sec:'A',ts:'q',
 tip:'The institution is “Parliamentary Library, Legislature”, or the jurisdiction’s own research service, eg Parliamentary Research Service (NSW).',
 f:PAPER('Research Paper','Library, legislature','Parliamentary Library, Parliament of Australia'),
 ex:{au:[person('Harriet','Moss')],title:'Satellite broadband and regional connectivity: a quick guide',dtype:'Research Paper',dno:'3',inst:'Parliamentary Library, Parliament of Australia',date:'18 September 2025'},
 cite:paperCite},
{id:'paper-conf',cat:'papers',name:'Conference paper',rule:'7.2.4',k:'sec',sec:'A',ts:'q',
 tip:'Leave out ordinal numbers such as “23rd”, and the city unless it is part of the forum’s name. If the paper was later published, cite the journal or book version.',
 f:PAPER('Conference Paper','Conference / forum','Future of Contract Law Symposium'),
 ex:{au:[person('Daniel','Ferro')],title:'Smart contracts as deeds?',dtype:'Conference Paper',inst:'Future of Contract Law Symposium',date:'12 November 2024'},
 cite:paperCite},
{id:'thesis',cat:'papers',name:'Thesis / dissertation',rule:'7.2.5',k:'sec',sec:'A',ts:'q',
 tip:'The document type is the degree, eg PhD Thesis, LLM Thesis or Honours Thesis. Name the university only; leave out the faculty or college.',
 f:[AU(),T('title','Title',{w:2,req:1,title:1}),T('dtype','Degree',{req:1,ph:'PhD Thesis'}),T('inst','University',{req:1}),T('date','Year',{req:1}),PIN('112')],
 ex:{au:[person('Aisha','Rahman')],title:'Governing the deep seabed: common heritage in an age of extraction',dtype:'PhD Thesis',inst:'University of New Westland',date:'2023',pin:'112'},
 cite:paperCite},
{id:'speech',cat:'papers',name:'Speech / lecture',rule:'7.3',k:'sec',sec:'E',ts:'q',
 tip:'For a named lecture, put the lecture’s name in place of “Speech” (without a leading “The” or an ordinal). Give the city only if no forum is named. Sitting judges keep their title, eg Justice.',
 f:[AU('au','Speaker'),T('title','Title',{w:2,req:1,title:1}),T('kind','Speech or lecture name',{ph:'Speech'}),T('forum','Institution / forum (or city)',{req:1}),DATE('date','Full date',{req:1}),PIN('4')],
 ex:{au:[person('Justice Rowan','Ellery')],title:'Courts, code and candour',kind:'Speech',forum:'Law Institute Annual Dinner',date:'4 March 2025'},
 cite:d=>J(authorsText(d.au,d._bib),Q(d.title))+` (${J(d.kind||'Speech',d.forum,d.date)})`+(d.pin?' '+d.pin:'')},

/* ---------------- REFERENCE WORKS ---------------- */
{id:'dict',cat:'ref',name:'Dictionary entry',rule:'7.6',k:'other',sec:'A',ts:'i',st:false,
 tip:'For an online dictionary, give the date you retrieved the entry. Use “def” for a numbered definition, and the dictionary’s own label (eg n, adj) where a word has several entries.',
 f:[T('title','Dictionary',{w:2,req:1,ph:'Macquarie Dictionary'}),S('mode','Format',[['online','Online'],['print','Print']]),T('edn','Edition',{when:d=>d.mode==='print'}),T('year','Year',{when:d=>d.mode==='print',req:1}),DATE('date','Date retrieved',{when:d=>d.mode==='online',req:1}),T('entry','Entry',{req:1,ph:'deepfake'}),T('label','Part of speech / entry label',{ph:'n'}),T('def','Definition number',{ph:'1'})],
 ex:{title:'Macquarie Dictionary',mode:'online',date:'21 September 2026',entry:'deepfake',def:'1'},
 cite:d=>`${I(d.title)} (${d.mode==='online'?'online at '+d.date:J(d.edn?ord(d.edn)+' ed':'',d.year)}) ‘${d.entry}’`+((d.label||d.def)?` (${J(d.label,d.def?'def '+d.def:'')})`:''),
 txt:d=>({first:`the ${I(d.title)} definition of ‘${d.entry}’`,later:`‘${d.entry}’`}),subHead:d=>I(d.title)},
{id:'encyc',cat:'ref',name:'Legal encyclopedia',rule:'7.7',k:'other',sec:'A',ts:'i',st:false,
 tip:'For example Halsbury’s Laws of Australia or The Laws of Australia. Pinpoints are to paragraphs. Online entries take the date you retrieved them.',
 f:[T('pub','Publisher',{req:1,ph:'LexisNexis'}),T('title','Encyclopedia',{req:1,ph:'Halsbury’s Laws of Australia'}),S('mode','Format',[['online','Online'],['print','Print']]),T('vol','Volume',{when:d=>d.mode==='print'}),DATE('date','Date (at / online at)',{req:1}),T('tno','Title number',{ph:'130'}),T('tname','Title name',{req:1,ph:'Communications'}),T('ch','Chapter (number and name)',{w:2,req:1,ph:'7 Online Safety'}),PIN('[130-7015]','Paragraph',{nodash:1})],
 ex:{pub:'LexisNexis',title:'Halsbury’s Laws of Australia',mode:'online',date:'21 September 2026',tno:'130',tname:'Communications',ch:'7 Online Safety',pin:'[130-7015]'},
 cite:d=>`${J(d.pub,I(d.title),d.mode==='print'&&d.vol?'vol '+d.vol:'')} (${d.mode==='online'?'online at':'at'} ${d.date}) ${SP(d.tno,d.tname)}, ‘${d.ch}’`+(d.pin?' '+d.pin:''),
 txt:d=>({first:I(d.title),later:I(d.title)}),subHead:d=>`${d.pub}, ${I(d.title)}`,sort:d=>d.pub},
{id:'looseleaf',cat:'ref',name:'Looseleaf service',rule:'7.8',k:'sec',sec:'A',ts:'i',
 tip:'Pinpoints are to paragraphs. Where the service uses the ¶ symbol, put it before the number and drop the square brackets.',
 f:[AU('au','Author (if clearly identified)'),T('pub','Publisher',{req:1,ph:'Thomson Reuters'}),T('title','Title',{w:2,req:1,title:1}),S('mode','Format',[['print','Print'],['online','Online']]),T('vol','Volume',{when:d=>d.mode==='print'}),T('svc','Service number or date',{when:d=>d.mode==='print',ph:'Service 88'}),DATE('date','Date retrieved',{when:d=>d.mode==='online',req:1}),PIN('[4.120]','',{nodash:1})],
 ex:{au:[person('Neil','Tarrant')],pub:'Thomson Reuters',title:'Privacy law and practice',mode:'print',vol:'1',svc:'Service 88',pin:'[4.120]'},
 cite:d=>J(authorsText(d.au,d._bib),d.pub,I(d.title),d.mode==='print'&&d.vol?'vol '+d.vol:'')+` (${d.mode==='online'?'online at '+d.date:'at '+d.svc})`+(d.pin?' '+d.pin:'')},
{id:'ip',cat:'ref',name:'Patent / trade mark / design',rule:'7.9',k:'other',sec:'E',
 tip:'Use the WIPO ST.3 jurisdiction code (AU, US, EM…) and the IP type exactly as the registration documents word it. Prefer a registration number where one exists.',
 f:[T('code','Jurisdiction code',{req:1,ph:'AU'}),T('ipt','IP type',{req:1,ph:'Patent'}),T('add','Number type (optional)',{ph:'Application',help:'eg Registration, Application, Filing, Serial'}),T('num','Number',{req:1}),DATE('date','Filed / lodged on',{req:1}),T('status','Latest status change',{ph:'Granted'}),DATE('sdate','Date of status change')],
 ex:{code:'AU',ipt:'Patent',add:'Application',num:'2024901234',date:'3 April 2024',status:'Granted',sdate:'19 June 2026'},
 cite:d=>`${SP(d.code,d.ipt,d.add)} No ${d.num}, filed on ${d.date}`+(d.status?` (${d.status} on ${d.sdate||miss('date')})`:''),
 txt:d=>({first:`${SP(d.code,d.ipt,d.add)} No ${d.num}`,later:d.st||`${d.ipt} No ${d.num}`}),subHead:d=>d.st||`${SP(d.code,d.ipt,d.add)} No ${d.num}`},
{id:'corpdoc',cat:'ref',name:'Company constitution / charter',rule:'7.10',k:'other',sec:'E',
 tip:'Leave “Pty”, “Ltd”, “Inc” and a leading “The” out of the company name. Use the date of last update if shown, otherwise the date you retrieved it. Pinpoints are to clauses, not pages.',
 f:[T('dtype','Document type',{req:1,ph:'Constitution'}),T('co','Company',{req:1,ph:'Helios Launch Services'}),DATE('date','Date (at …)',{req:1}),PIN('cl 12.3','',{nodash:1})],
 ex:{dtype:'Constitution',co:'Helios Launch Services',date:'1 July 2025',pin:'cl 12.3'},
 cite:d=>`${d.dtype}, ${d.co.replace(/\s+(Pty|Ltd|Inc|Limited)\b\.?/g,'')} (at ${d.date})`+(d.pin?' '+d.pin:''),
 txt:d=>({first:`the ${d.co} ${d.dtype.toLowerCase()}`,later:d.st||`the ${d.dtype.toLowerCase()}`}),subHead:d=>d.st||`${d.dtype}, ${d.co}`,sort:d=>d.dtype},

/* ---------------- MEDIA & ONLINE ---------------- */
{id:'news',cat:'media',name:'Newspaper (print)',rule:'7.11.1',k:'sec',sec:'A',ts:'q',
 tip:'Use the masthead’s full name, including “The”. Name the section only if the paper isn’t paginated consecutively. For an editorial, pick “Editorial” as the author type.',
 f:[S('akind','Author',[['au','Named author(s)'],['ed','Editorial'],['none','Unsigned']]),AU('au','Author(s)',{when:d=>d.akind==='au'}),C('untitled','Untitled piece (use a description, eg Letter to the Editor)'),T('title','Title / description',{w:2,req:1,title:1}),T('section','Section (optional)',{ph:'Business'}),T('paper','Newspaper',{req:1,ph:'The Westland Herald'}),T('edition','Edition (optional)',{ph:'Late Edition'}),T('place','Place of publication',{req:1,ph:'Melbourne'}),DATE('date','Full date',{req:1}),PIN('5')],
 ex:{akind:'au',au:[person('Ruby','Tanaka')],title:'Drone deliveries take off in the suburbs',paper:'The Westland Herald',place:'Melbourne',date:'9 June 2025',pin:'5'},
 cite:d=>{const a=d.akind==='ed'?'Editorial':d.akind==='au'?authorsText(d.au,d._bib):'';return J(a,d.untitled?d.title:Q(d.title),d.section,I(d.paper))+` (${J(d.edition,d.place,d.date)})`+(d.pin?' '+d.pin:'');},
 auF:d=>d.akind==='au'?'au':null},
{id:'news-online',cat:'media',name:'Newspaper (online)',rule:'7.11.2',k:'sec',sec:'A',ts:'q',url:1,
 tip:'Write “online” in place of the place of publication and finish with the URL. Include a pinpoint only if the article has pages or paragraphs.',
 f:[AU(),T('title','Title',{w:2,req:1,title:1}),T('paper','Newspaper',{req:1,ph:'The Coastal Times'}),DATE('date','Full date',{req:1}),PIN('')],
 ex:{au:[person('Callum','Reid')],title:'Court rules on AI-generated evidence',paper:'The Coastal Times',date:'22 August 2025',url:'https://www.example.com/news/court-rules-ai-evidence'},
 cite:d=>{if(!d.url&&!d._bib)d._w.push(['warn','Online newspaper citations need a URL (r 7.11.2).']);return J(authorsText(d.au,d._bib),Q(d.title),I(d.paper))+` (online, ${d.date})`+(d.pin?' '+d.pin:'');}},
{id:'magazine',cat:'media',name:'Magazine / newsletter',rule:'7.11.3',k:'sec',sec:'A',ts:'q',url:1,
 tip:'Use this where an issue is identified by date, month or season rather than by volume and number. Otherwise treat it as a journal article.',
 f:[AU(),T('title','Title',{w:2,req:1,title:1}),T('date','Date / month / season',{req:1,date:1,ph:'Winter 2024'}),T('mag','Magazine / newsletter',{req:1}),PIN('22')],
 ex:{au:[person('Nina','Park')],title:'The law of lunar real estate',date:'Winter 2024',mag:'Future Counsel',pin:'22'},
 cite:d=>J(authorsText(d.au,d._bib),Q(d.title))+` (${d.date}) ${I(d.mag)}`+(d.pin?' '+d.pin:'')},
{id:'web',cat:'media',name:'Web page / blog post',rule:'7.15',k:'sec',sec:'E',ts:'q',tf:'dtitle',url:1,
 tip:'Use this only if no other rule fits. Include an author only if the page names one. The website title is italicised like a book. Use “Web Page” when the document type isn’t clear.',
 f:[AU('au','Author (only if shown)'),T('dtitle','Document title',{w:2,req:1,title:1}),T('site','Website title',{w:2,req:1}),T('dtype','Document type',{ph:'Web Page',help:'eg Blog Post, Forum Post, Web Page'}),DATE('date','Date (last updated)'),PIN('[4]')],
 ex:{au:[],dtitle:'Guidance on automated decision-making',site:'Office of the Digital Rights Commissioner',dtype:'Web Page',date:'3 May 2025',url:'https://www.example.org/guidance/automated-decisions'},
 cite:d=>{if(!d.url&&!d._bib)d._w.push(['warn','Internet materials need a URL after the first reference (r 7.15).']);return J(authorsText(d.au,d._bib),Q(d.dtitle),I(d.site))+` (${J(d.dtype||'Web Page',d.date)})`+(d.pin?' '+d.pin:'');}},
{id:'social',cat:'media',name:'Social media / YouTube',rule:'7.16',k:'other',sec:'E',url:1,
 tip:'Copy the username exactly, including “@” on X/Twitter. Add the time and time zone when the platform adjusts times or when the account posted more than once that day.',
 f:[T('user','Username',{req:1,raw:1,ph:'@LexOrbit'}),T('who','Real name (optional)',{ph:'Priya Venkataraman'}),T('title','Post / video title (if any)',{w:2}),T('plat','Platform',{req:1,list:'dl-platform'}),DATE('date','Full date',{req:1}),T('time','Time and time zone',{ph:'9:12am AEDT',help:'No space before am/pm (r 1.11.2).'}),PIN('0:01:10–0:02:30','Videos: time span')],
 ex:{user:'@LexOrbit',who:'Priya Venkataraman',plat:'X',date:'14 January 2025',time:'9:12am AEDT',url:'https://x.com/LexOrbit/status/1234567890'},
 cite:d=>{if(!d.url&&!d._bib)d._w.push(['warn','Social media posts need a URL, plus an archived link if the post may be deleted (r 7.16).']);return d.user+(d.who?` (${d.who})`:'')+(d.title?`, ${Q(d.title)}`:'')+` (${J(d.plat,d.date,d.time.replace(/\s+(am|pm)\b/i,'$1'))})`+(d.pin?' '+d.pin:'');},
 txt:d=>({first:d.title?`${Q(d.title)} by ${d.user}`:`a post by ${d.user}`+(d.who?` (${d.who})`:''),later:d.user}),subHead:d=>d.st||d.user},
{id:'film',cat:'media',name:'Film / audiovisual',rule:'7.14.2',k:'other',sec:'E',ts:'i',url:1,
 tip:'Give version details (eg Director’s Cut) only if you are not citing the standard version. Name only the first studio listed. Pinpoint to a time.',
 f:[T('title','Film title',{w:2,req:1,title:1}),T('ver','Version (non-standard only)'),T('studio','Studio / production company',{req:1}),T('year','Year',{req:1}),PIN('1:02:10–1:04:45')],
 ex:{title:'Signal lost',studio:'Meridian Pictures',year:'2022',pin:'1:02:10-1:04:45'},
 cite:d=>`${I(d.title)} (${J(d.ver,d.studio,d.year)})`+(d.pin?' '+d.pin:'')},
{id:'tv',cat:'media',name:'Television episode / series',rule:'7.14.3',k:'other',sec:'E',ts:'i',tf:'series',url:1,
 tip:'An untitled episode becomes ‘Episode 4’ or ‘Season 2, Episode 4’. For a whole series, leave the episode blank and use the production details of the first episode.',
 f:[T('ep','Episode title',{w:2,title:1,ph:'The Quiet Algorithm'}),T('series','Series title',{w:2,req:1,title:1}),T('ver','Version (non-standard only)'),T('prod','Production company / network',{req:1}),T('year','Year',{req:1}),PIN('0:21:30')],
 ex:{ep:'The quiet algorithm',series:'Justice protocol',prod:'Southern Cross Studios',year:'2024',pin:'0:21:30'},
 cite:d=>(d.ep?Q(d.ep)+', ':'')+`${I(d.series)} (${J(d.ver,d.prod,d.year)})`+(d.pin?' '+d.pin:''),sort:d=>d.ep||d.series},
{id:'podcast',cat:'media',name:'Podcast / radio segment',rule:'7.14.4',k:'other',sec:'E',ts:'i',tf:'series',url:1,
 tip:'Use the episode title as it appears on the listening platform. Leave the producer out if it has the same name as the series. The date follows the time zone the podcast comes from.',
 f:[T('ep','Episode title',{w:2,req:1,ph:'Episode 42: Who Owns a Satellite?'}),T('series','Podcast / program',{w:2,req:1}),T('prod','Producer / station',{help:'Omit if identical to the series title.'}),DATE('date','Full date',{req:1}),PIN('00:14:20')],
 ex:{ep:'Episode 42: Who Owns a Satellite?',series:'Orbit & Order',prod:'Lex Futura Media',date:'3 March 2025',pin:'00:14:20'},
 cite:d=>`${Q(d.ep)}, ${I(d.series)} (${J(d.prod&&pl(d.prod)!==pl(d.series)?d.prod:'',d.date)})`+(d.pin?' '+d.pin:''),sort:d=>d.ep},
{id:'corr',cat:'media',name:'Letter / email',rule:'7.12',k:'other',sec:'E',url:1,
 tip:'Positions may follow the names. For archived correspondence, add the archive details in brackets after the date.',
 f:[S('kind','Type',[['Email','Email'],['Letter','Letter'],['Fax','Fax']]),T('from','From',{req:1,clean:'name',ph:'Wen Liu, Chief Data Officer'}),T('to','To',{req:1,clean:'name'}),DATE('date','Full date',{req:1}),T('arch2','Archive details (optional)',{w:2}),PIN('2')],
 ex:{kind:'Email',from:'Wen Liu, Chief Data Officer',to:'Tessa Marlow',date:'17 April 2025'},
 cite:d=>`${d.kind} from ${d.from} to ${d.to}, ${d.date}`+(d.arch2?` (${d.arch2})`:'')+(d.pin?', '+d.pin:''),
 txt:d=>({first:`${d.from.split(',')[0]}’s ${d.kind.toLowerCase()} to ${d.to.split(',')[0]}`,later:d.st||`the ${d.kind.toLowerCase()}`}),subHead:d=>d.st||`${d.kind} from ${d.from} to ${d.to}`},
{id:'interview',cat:'media',name:'Interview / conversation',rule:'7.13',k:'other',sec:'E',url:1,
 tip:'Swap “Interview” for another format where it fits, eg “Conversation”. A televised interview can instead be cited as television.',
 f:[S('fmt','Format',[['Interview','Interview'],['Conversation','Conversation']]),T('who','Interviewee',{req:1,clean:'name'}),T('pos','Position (optional)',{w:2}),T('by','Interviewer',{req:1,clean:'name'}),T('forum','Forum (optional)'),DATE('date','Full date',{req:1})],
 ex:{fmt:'Interview',who:'Tessa Marlow',pos:'Director, Centre for Space Law',by:'Jordan Blake',forum:'Orbit & Order',date:'2 March 2025'},
 cite:d=>`${d.fmt} with ${J(d.who,d.pos)} (${J(d.by,d.forum,d.date)})`,
 txt:d=>({first:`an ${d.fmt.toLowerCase()} with ${d.who}`,later:d.st||d.who}),subHead:d=>d.st||`${d.fmt} with ${d.who}`},

/* ---------------- INTERNATIONAL ---------------- */
{id:'treaty',cat:'intl',name:'Treaty',rule:'8',k:'tr',sec:'D',ts:'i',
 tip:'List parties only for bilateral or trilateral treaties, and only if they aren’t already in the title. Prefer the UNTS or LNTS, then a state party’s official series. Pinpoints are to articles, not pages.',
 f:[T('title','Treaty title',{w:2,req:1}),T('parties','Parties (bilateral / trilateral)',{w:2,ph:'Australia, Veloria',help:'Separate with commas. They are joined with en-dashes.'}),S('mode','Conclusion',[['open','Opened for signature (multilateral)'],['signed','Signed by all parties'],['same','Signed and entered into force same day']],{w:2}),DATE('date','Date opened / signed',{req:1}),T('series','Treaty series',{req:1,list:'dl-series-tr',ph:'610 UNTS 205',help:'eg 993 UNTS 3, [2001] ATS 18, ETS No 185'}),C('nyif','Not yet in force'),DATE('eif','Entry into force',{when:d=>d.mode!=='same'&&!d.nyif,req:1}),PIN('art II','',{nodash:1})],
 ex:{title:'Treaty on Principles Governing the Activities of States in the Exploration and Use of Outer Space, including the Moon and Other Celestial Bodies',mode:'open',date:'27 January 1967',series:'610 UNTS 205',eif:'10 October 1967',pin:'art II',st:'Outer Space Treaty'},
 cite:d=>{const pt=d.parties?d.parties.split(/\s*[,;]\s*/).filter(Boolean).join('–'):'';let s=J(I(d.title),pt);
   if(d.mode==='same')return s+`, ${d.series} (signed and entered into force ${d.date})`+(d.pin?' '+d.pin:'');
   s+=`, ${d.mode==='open'?'opened for signature':'signed'} ${d.date}, ${d.series} (${d.nyif?'not yet in force':'entered into force '+d.eif})`;return s+(d.pin?' '+d.pin:'');}},
{id:'mou',cat:'intl',name:'Memorandum of understanding',rule:'8.6',k:'tr',sec:'D',ts:'i',url:1,
 tip:'Add “(Memorandum of Understanding)” after the date only when those words aren’t already in the title. When they are, put a comma before the pinpoint.',
 f:[T('title','Title',{w:2,req:1}),T('parties','Parties',{w:2,ph:'Australia, Veloria'}),DATE('date','Date signed',{req:1}),T('series','Treaty series (if any)'),PIN('s 2','',{nodash:1})],
 ex:{title:'Memorandum of Understanding on Space Situational Awareness Cooperation',parties:'Australia, Veloria',date:'8 May 2024',pin:'s 2'},
 cite:d=>{const pt=d.parties?d.parties.split(/\s*[,;]\s*/).filter(Boolean).join('–'):'';const inT=/memorandum of understanding/i.test(pl(d.title));let s=J(I(d.title),pt,'signed '+d.date,d.series);if(!inT)s+=' (Memorandum of Understanding)'+(d.pin?' '+d.pin:'');else if(d.pin)s+=', '+d.pin;return s;}},
{id:'charter',cat:'intl',name:'UN Charter / ICJ Statute',rule:'9.1 · 10.1',k:'tr',sec:'D',st:false,
 tip:'These founding documents are cited by title and pinpoint only, with no treaty series details.',
 f:[S('doc','Document',[['Charter of the United Nations','Charter of the United Nations'],['Statute of the International Court of Justice','Statute of the International Court of Justice']],{w:2}),PIN('art 2(4)','',{nodash:1,w:2})],
 ex:{doc:'Charter of the United Nations',pin:'art 2(4)'},
 cite:d=>SP(I(d.doc),d.pin),txt:d=>({first:'the '+I(d.doc),later:'the '+I(d.doc.includes('Charter')?'Charter':'Statute')}),subHead:d=>I(d.doc)},
{id:'unres',cat:'intl',name:'UN resolution',rule:'9.2.3',k:'un',sec:'E',ts:'i',
 tip:'Official Records details can be left out when the document is easy to find online by its UN document number. Operative paragraphs are cited as “para 3”, preambular ones as “Preamble para 2”.',
 f:[T('title','Title (if any)',{w:2}),S('organ','Organ and type',[['GA Res','GA Res'],['SC Res','SC Res'],['ESC Res','ESC Res'],['GA Dec','GA Dec'],['SC Dec','SC Dec'],['ESC Dec','ESC Dec']]),T('num','Resolution number',{req:1,ph:'80/115'}),T('doc','UN document number',{req:1,raw:1,ph:'A/RES/80/115'}),DATE('date','Date (below doc number)',{req:1}),DATE('adopted','Date adopted (if different)'),PIN('para 4','',{nodash:1})],
 ex:{title:'Responsible Behaviour in Orbital Operations',organ:'GA Res',num:'80/115',doc:'A/RES/80/115',date:'12 December 2025',adopted:'5 December 2025',pin:'para 4',st:'Orbital Operations Resolution'},
 cite:d=>J(I(d.title),`${d.organ} ${d.num}`,`UN Doc ${d.doc}`)+` (${J(d.date,d.adopted?'adopted '+d.adopted:'')})`+(d.pin?' '+d.pin:''),
 subHead:d=>`${d.st?I(d.st):(d.title?I(d.title):d.organ+' '+d.num)}, UN Doc ${d.doc}`,txt:d=>({first:d.title?I(d.title):`${d.organ.replace('GA','General Assembly').replace('SC','Security Council').replace('ESC','Economic and Social Council').replace('Res','Resolution').replace('Dec','Decision')} ${d.num}`,later:d.st?I(d.st):`Resolution ${d.num}`})},
{id:'undoc',cat:'intl',name:'UN document (general)',rule:'9.2',k:'un',sec:'E',ts:'i',
 tip:'Fill in only the elements that appear on the document, in the order shown. Ordinals such as 60th are superscripted automatically.',
 f:[T('author','Author (person or subsidiary body)',{w:2}),T('title','Title',{w:2}),T('rec','Official Records',{ph:'UN GAOR'}),T('comm','Committee number',{ph:'3',help:'Becomes “3rd Comm”'}),T('sess','Session',{ph:'64',help:'Becomes “64th sess”'}),T('mtg','Meeting',{ph:'12'}),C('plen','Plenary meeting'),T('agenda','Agenda item(s)',{ph:'49(b)'}),T('supp','Supplement number'),T('doc','UN document number',{req:1,raw:1,ph:'A/AC.105/1330'}),DATE('date','Full date',{req:1}),DATE('adopted','Date adopted (optional)'),T('annex','Annex (optional)',{ph:'annex I'}),PIN('14 [42]','Paragraph numbers in [ ] for reports',{nodash:1})],
 ex:{author:'Committee on the Peaceful Uses of Outer Space',title:'Report of the Legal Subcommittee on Its Sixty-Fourth Session',doc:'A/AC.105/1330',date:'18 April 2025',pin:'14 [42]'},
 cite:d=>{const o=v=>v?ord(v):'';const agendaItems=/\band\b|,/.test(pl(d.agenda))?'Agenda Items ':'Agenda Item ';
   return J(d.author,I(d.title),d.rec,d.comm?o(d.comm)+' Comm':'',d.sess?o(d.sess)+' sess':'',d.mtg?o(d.mtg)+(d.plen?' plen mtg':' mtg'):'',d.agenda?agendaItems+d.agenda:'',d.supp?'Supp No '+d.supp:'',`UN Doc ${d.doc}`)+` (${J(d.date,d.adopted?'adopted '+d.adopted:'')})`+(d.annex?' '+d.annex:'')+(d.pin?' '+d.pin:'');},
 subHead:d=>`${d.st?I(d.st):(d.title?I(d.title):d.author)}, UN Doc ${d.doc}`,sort:d=>d.author||d.title},
{id:'uncomm',cat:'intl',name:'UN treaty committee decision',rule:'9.3.1',k:'un',sec:'E',st:true,
 tip:'Decisions on individual communications always get a short title in the form (Complainant v State).',
 f:[T('comm','Committee',{w:2,req:1,ph:'Human Rights Committee'}),T('dtype','Decision type',{ph:'Views'}),T('cno','Communication number',{req:1,ph:'3901/2021'}),T('sess','Session',{ph:'139'}),T('doc','UN document number',{req:1,raw:1}),DATE('date','Full date',{req:1}),PIN('[8.4]','',{nodash:1})],
 ex:{comm:'Human Rights Committee',dtype:'Views',cno:'3901/2021',sess:'139',doc:'CCPR/C/139/D/3901/2021',date:'14 November 2023',pin:'[8.4]',st:'Halvorsen v Veloria'},
 cite:d=>{if(!d.st&&!d._bib)d._w.push(['warn','Add a short title in the form “Complainant v State” (r 9.3.1).']);return J(d.comm,I(`${d.dtype||'Views'}: Communication No ${d.cno}`),d.sess?ord(d.sess)+' sess':'',`UN Doc ${d.doc}`)+` (${d.date})`+(d.pin?' '+d.pin:'');},
 stS:'i',subHead:d=>`${d.st?I(d.st):d.comm}, UN Doc ${d.doc}`,txt:d=>({first:d.st?I(d.st):`the ${d.comm}’s views`,later:d.st?I(d.st):'the decision'}),sort:d=>d.comm},
{id:'icj',cat:'intl',name:'ICJ / PCIJ decision',rule:'10.2 · 10.4',k:'case',sec:'B',
 tip:'Leave out “The”, “Case concerning” and a trailing “Case”. Parties go in parentheses separated by “v”, or use “Advisory Opinion” as the phase. Name a judge only for separate or dissenting opinions.',
 f:[T('name','Case name',{w:2,req:1,ph:'Orbital Debris'}),T('parties','Parties (leave blank for an advisory opinion)',{w:2,ph:'Veloria v Norland'}),T('phase','Phase',{req:1,ph:'Preliminary Objections'}),S('mode','Status',[['rep','Reported (ICJ Rep / PCIJ)'],['unrep','Unreported (General List)']]),
   T('year','Year',{req:1,when:d=>d.mode==='rep'}),T('series','Series',{when:d=>d.mode==='rep',ph:'ICJ Rep',help:'For the PCIJ, eg PCIJ (ser A) No 7'}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),
   T('gl','General List number',{when:d=>d.mode==='unrep',req:1}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('130 [48]'),T('jj','Judge (separate / dissenting)',{pin:1,ph:'Judge Adeyemi'})],
 ex:{name:'Orbital Debris',parties:'Veloria v Norland',phase:'Preliminary Objections',mode:'rep',year:'2024',series:'ICJ Rep',page:'112',pin:'130 [48]',st:'Orbital Debris'},
 cite:d=>{const head=I(d.name)+(d.parties?` (${I(d.parties)})`:'')+` (${I(d.phase)})`;const tail=(d.pin?', '+d.pin:'')+(d.pin&&d.jj?` (${d.jj})`:'');
   if(d.mode==='unrep')return head+` (International Court of Justice, General List No ${d.gl}, ${d.date})`+(d.pin?' '+d.pin:'')+(d.pin&&d.jj?` (${d.jj})`:'');
   return head+` [${d.year}] ${d.series||'ICJ Rep'} ${d.page}`+tail;}},
{id:'arb-state',cat:'intl',name:'State–state arbitration',rule:'11.1',k:'case',sec:'B',
 tip:'A reported award is cited like an ICJ decision, using the RIAA or another series. For an unreported award, give the tribunal’s name as it appears on the award.',
 f:[T('name','Case name',{w:2,req:1,ph:'Kestrel Strait Arbitration'}),T('parties','Parties',{w:2,req:1,ph:'Veloria v Norland'}),T('phase','Phase',{req:1,ph:'Award'}),S('mode','Status',[['unrep','Unreported'],['rep','Reported']]),
   T('year','Year',{when:d=>d.mode==='rep',req:1}),T('vol','Volume',{when:d=>d.mode==='rep'}),T('series','Series',{when:d=>d.mode==='rep',ph:'RIAA'}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),
   T('trib','Arbitral body / tribunal',{w:2,when:d=>d.mode==='unrep',req:1,ph:'Permanent Court of Arbitration'}),T('caseno','Case number',{when:d=>d.mode==='unrep'}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('[214]')],
 ex:{name:'Kestrel Strait Arbitration',parties:'Veloria v Norland',phase:'Award',mode:'unrep',trib:'Permanent Court of Arbitration',caseno:'Case No 2021-14',date:'30 June 2023',pin:'[214]'},
 cite:d=>{const head=`${I(d.name)} (${I(d.parties)}) (${I(d.phase)})`;if(d.mode==='rep')return head+` (${d.year}) ${SP(d.vol,d.series||'RIAA',d.page)}`+(d.pin?', '+d.pin:'');return head+` (${J(d.trib,d.caseno,d.date)})`+(d.pin?' '+d.pin:'');}},
{id:'arb-inv',cat:'intl',name:'Investor–state arbitration',rule:'11.2',k:'case',sec:'B',
 tip:'Name the parties as in r 2.1. Include a phase only if the decision gives one, and cite the ICSID Reports where the award is reported.',
 f:[T('name','Parties',{w:2,req:1,clean:'case',ph:'Aurora Satellite Systems Inc v Veloria'}),T('phase','Phase',{ph:'Award'}),S('mode','Status',[['unrep','Unreported'],['rep','Reported']]),
   T('year','Year',{when:d=>d.mode==='rep',req:1}),T('vol','Volume',{when:d=>d.mode==='rep'}),T('series','Series',{when:d=>d.mode==='rep',ph:'ICSID Rep'}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),
   T('trib','Tribunal',{when:d=>d.mode==='unrep',req:1,ph:'ICSID Arbitral Tribunal'}),T('caseno','Case number',{when:d=>d.mode==='unrep',ph:'Case No ARB/20/7'}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('[158]')],
 ex:{name:'Aurora Satellite Systems Inc v Veloria',phase:'Award',mode:'unrep',trib:'ICSID Arbitral Tribunal',caseno:'Case No ARB/20/7',date:'11 September 2024',pin:'[158]',st:'Aurora (Award)'},
 cite:d=>{const head=I(d.name)+(d.phase?` (${I(d.phase)})`:'');if(d.mode==='rep')return head+` (${d.year}) ${SP(d.vol,d.series||'ICSID Rep',d.page)}`+(d.pin?', '+d.pin:'');return head+` (${J(d.trib,d.caseno,d.date)})`+(d.pin?' '+d.pin:'');}},
{id:'icc',cat:'intl',name:'International criminal tribunal',rule:'12.2',k:'case',sec:'B',
 tip:'Parties appear as “Prosecutor v Surname”, reversed on appeal where the decision reverses them. Chamber numbers are in Roman numerals. Pinpoints are to paragraphs.',
 f:[T('name','Parties',{w:2,req:1,ph:'Prosecutor v Draven'}),T('phase','Phase',{req:1,w:2,ph:'Judgment'}),T('court','Tribunal / court',{w:2,req:1,ph:'International Criminal Court'}),T('chamber','Chamber',{ph:'Trial Chamber IV'}),T('caseno','Case number',{req:1,raw:1,ph:'ICC-02/19-01/21'}),DATE('date','Full date',{req:1}),PIN('[412]'),T('jj','Judge (separate opinion)',{pin:1})],
 ex:{name:'Prosecutor v Draven',phase:'Judgment',court:'International Criminal Court',chamber:'Trial Chamber IV',caseno:'ICC-02/19-01/21',date:'27 February 2026',pin:'[412]',st:'Draven (Trial Judgment)'},
 cite:d=>`${I(d.name)} (${I(d.phase)}) (${J(d.court,d.chamber,'Case No '+d.caseno,d.date)})`+(d.pin?' '+d.pin:'')+(d.pin&&d.jj?` (${d.jj})`:'')},
{id:'wto',cat:'intl',name:'WTO / GATT dispute report',rule:'13.1.3',k:'case',sec:'B',
 tip:'Begin with the report type. The case name is italicised. Short titles use the conventional form, eg US — Zeroing (Article 21.5 — Japan).',
 f:[S('kind','Report type',[['Panel Report','Panel Report'],['Appellate Body Report','Appellate Body Report'],['Decision by the Arbitrator','Decision by the Arbitrator'],['GATT Panel Report','GATT Panel Report']],{w:2}),T('name','Case name',{w:2,req:1,ph:'Veloria — Measures Affecting the Importation of Satellite Components'}),T('doc','Document number',{req:1,raw:1,ph:'WT/DS642/R'}),DATE('date','Date circulated',{req:1}),DATE('adopted','Date adopted'),T('dsr','DSR / BISD reference (optional)'),PIN('[7.28]–[7.50]')],
 ex:{kind:'Panel Report',name:'Veloria -- Measures Affecting the Importation of Satellite Components',doc:'WT/DS642/R',date:'16 October 2025',adopted:'',pin:'[7.28]-[7.50]',st:'Veloria -- Satellite Components'},
 cite:d=>{const nm=d.name.replace(/\s+-{1,2}\s+/g,' — ');return `${d.kind}, ${I(nm)}, ${d.kind.startsWith('GATT')?'GATT':'WTO'} Doc ${d.doc} (${J(d.date,d.adopted?'adopted '+d.adopted:'')})`+(d.dsr?' '+d.dsr+',':'')+(d.pin?' '+d.pin:'');},
 subHead:d=>`${d.kind}, ${I((d.st||d.name).replace(/\s+-{1,2}\s+/g,' — '))}, ${d.kind.startsWith('GATT')?'GATT':'WTO'} Doc ${d.doc}`,txt:d=>({first:I(d.name.replace(/\s+-{1,2}\s+/g,' — ')),later:I((d.st||d.name).replace(/\s+-{1,2}\s+/g,' — '))}),sort:d=>d.kind},
{id:'cjeu',cat:'intl',name:'Court of Justice of the EU',rule:'14.2.3',k:'case',sec:'B',
 tip:'Cite the ECR where the decision is reported. For a decision not in the ECR, give the court, case number, ECLI and date.',
 f:[T('name','Parties',{w:2,req:1,clean:'case',ph:'Datawatch Ireland v Minister for Communications'}),T('cno','Case number',{req:1,raw:1,ph:'C-311/24'}),S('mode','Status',[['unrep','Not in ECR'],['rep','Reported in ECR']]),
   T('year','Year',{when:d=>d.mode==='rep',req:1}),T('series','Report series',{when:d=>d.mode==='rep',ph:'ECR'}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),
   T('court','Court',{w:2,when:d=>d.mode==='unrep',ph:'Court of Justice of the European Union'}),T('ecli','ECLI',{when:d=>d.mode==='unrep',raw:1,ph:'ECLI:EU:C:2025:614'}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('[41]')],
 ex:{name:'Datawatch Ireland v Minister for Communications',cno:'C-311/24',mode:'unrep',court:'Court of Justice of the European Union',ecli:'ECLI:EU:C:2025:614',date:'10 September 2025',pin:'[41]'},
 cite:d=>d.mode==='rep'?`${I(d.name)} (${d.cno}) [${d.year}] ${d.series||'ECR'} ${d.page}`+(d.pin?', '+d.pin:''):`${I(d.name)} (${J(d.court||'Court of Justice of the European Union',d.cno,d.ecli,d.date)})`+(d.pin?' '+d.pin:'')},
{id:'echr',cat:'intl',name:'European Court of Human Rights',rule:'14.3.2',k:'case',sec:'B',
 tip:'Parties appear as “Complainant v Respondent State”. For a decision not in the official reports, give the chamber and application number.',
 f:[T('name','Parties',{w:2,req:1,ph:'Novak v Norland'}),T('phase','Phase (optional)'),S('mode','Status',[['unrep','Unreported'],['rep','Reported']]),
   T('repc','Report citation',{w:2,when:d=>d.mode==='rep',req:1,ph:'[2011] I Eur Court HR 255',help:'Year / volume / series / starting page.'}),
   T('chamber','Chamber',{when:d=>d.mode==='unrep',ph:'Grand Chamber'}),T('app','Application number(s)',{when:d=>d.mode==='unrep',req:1,ph:'40121/22'}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('[125]')],
 ex:{name:'Novak v Norland',mode:'unrep',chamber:'Grand Chamber',app:'40121/22',date:'5 March 2026',pin:'[125]'},
 cite:d=>{const head=I(d.name)+(d.phase?` (${I(d.phase)})`:'');if(d.mode==='rep')return `${head} ${d.repc}`+(d.pin?', '+d.pin:'');const nos=/\band\b|,/.test(d.app)?'Application Nos ':'Application No ';return head+` (${J('European Court of Human Rights',d.chamber,nos+d.app,d.date)})`+(d.pin?' '+d.pin:'');}},

/* ---------------- FOREIGN ---------------- */
{id:'fcase',cat:'foreign',name:'UK / NZ / Canadian case',rule:'15.1 · 21.1 · 24.1',k:'case',sec:'B',
 tip:'Cited like Australian cases. Add the court in brackets where it isn’t apparent from the series, eg (Supreme Court of New Zealand). Scottish reports such as SC and SLT have no brackets around the year.',
 f:[S('mode','Citation form',[['mnc','Neutral citation, eg [2024] UKSC 19'],['rep','Reported, eg [2009] 1 NZLR 351']],{w:2}),T('name','Case name',{w:2,req:1,clean:'case'}),{...YB,when:d=>d.mode==='rep'},T('year','Year',{req:1}),T('vol','Volume',{when:d=>d.mode==='rep'}),T('rep','Report series',{list:'dl-series',when:d=>d.mode==='rep',req:1}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),T('court','Court identifier / court',{list:'dl-mnc',req:1,when:d=>d.mode==='mnc'}),T('num','Judgment number',{when:d=>d.mode==='mnc',req:1}),PIN('[33]','',{para:d=>d.mode==='mnc'}),T('jj','Judicial officer(s)',{pin:1,ph:'Lord Ashcombe'})],
 ex:{mode:'mnc',yb:'square',name:'Halcyon Robotics Ltd v Pemberton',year:'2024',court:'UKSC',num:'19',pin:'33',jj:'Lord Ashcombe',st:'Halcyon Robotics'},
 cite:d=>d.mode==='rep'?caseRep(d):caseMnc(d)},
{id:'uk-act',cat:'foreign',name:'UK statute',rule:'24.2',k:'leg',sec:'C',
 tip:'Modern Acts take (UK), (Scot), (NI) or (Wales). Acts before 1963 may be cited with their regnal year and chapter. Imperial Acts take (Imp).',
 f:[T('title','Title (without year)',{w:2,req:1}),T('year','Year',{req:1}),T('jur','Jurisdiction (blank if regnal only)',{list:'dl-jur',ph:'UK'}),T('regnal','Regnal year (older Acts)',{ph:'9 & 10 Eliz 2'}),T('chap','Chapter',{when:d=>!!d.regnal,ph:'34'}),PIN('s 1','',{nodash:1})],
 ex:{title:'Automated Vehicles Act',year:'2024',jur:'UK',pin:'s 1'},
 cite:d=>{let s=I(SP(d.title,d.year))+(d.jur?` (${d.jur})`:'');if(d.regnal)s+=(d.jur?' ':', ')+`${d.regnal}, c ${d.chap}`;if(d.pin)s+=(d.regnal?', ':' ')+d.pin;return s;},txt:d=>({first:I(SP(d.title,d.year))+(d.jur?` (${d.jur})`:''),later:d.st?I(d.st):I(SP(d.title,d.year))})},
{id:'uk-si',cat:'foreign',name:'UK statutory instrument',rule:'24.3',k:'leg',sec:'C',
 tip:'Give the SI number after the jurisdiction. Northern Irish rules use SR, and older instruments SR & O.',
 f:[T('title','Title (without year)',{w:2,req:1}),T('year','Year',{req:1}),T('jur','Jurisdiction',{req:1,list:'dl-jur',ph:'UK'}),S('series','Series',[['SI','SI'],['SR','SR'],['SR & O','SR & O'],['SSI','SSI']]),T('num','Number',{req:1,ph:'2023/412'}),PIN('reg 4','',{nodash:1})],
 ex:{title:'Unmanned Aircraft (Registration) Regulations',year:'2023',jur:'UK',series:'SI',num:'2023/412',pin:'reg 4'},
 cite:d=>`${I(SP(d.title,d.year))} (${d.jur}) ${esc(d.series)} ${d.num}`+(d.pin?', '+d.pin:'')},
{id:'uk-hansard',cat:'foreign',name:'UK parliamentary debates',rule:'24.4.1',k:'other',sec:'E',
 tip:'Give the volume and column as well as the date. The speaker’s name follows in brackets.',
 f:[S('chamber','Chamber',[['House of Commons','House of Commons'],['House of Lords','House of Lords']],{w:2}),DATE('date','Full date',{req:1}),T('vol','Volume',{req:1}),T('col','Column',{req:1}),T('spk','Speaker',{clean:'name'})],
 ex:{chamber:'House of Commons',date:'4 February 2025',vol:'761',col:'1015',spk:'Eleanor Thorne'},
 cite:d=>J('United Kingdom',I('Parliamentary Debates'),d.chamber,d.date,'vol '+d.vol,'col '+d.col)+(d.spk?` (${d.spk})`:''),
 txt:d=>({first:`debate in the ${d.chamber} on ${d.date}`,later:d.spk||'the debate'}),subHead:d=>d.st||J('United Kingdom',I('Parliamentary Debates'),d.chamber,d.date)},
{id:'uk-cmd',cat:'foreign',name:'UK command paper',rule:'24.4.2',k:'sec',sec:'A',ts:'i',
 tip:'Cited like a report, with the command paper number (Cm, Cmnd, Cmd) and year in brackets.',
 f:[AU('au','Author (department)'),T('title','Title',{w:2,req:1,title:1}),T('paper','Command paper number',{req:1,ph:'Cm 9912'}),T('year','Year',{req:1}),PIN('12')],
 ex:{au:[body('Department for Science, Innovation and Technology (UK)')],title:'Regulating autonomous systems',paper:'Cm 9912',year:'2025',pin:'12'},
 cite:d=>`${J(authorsText(d.au,d._bib),I(d.title))} (${J(d.paper,d.year)})`+(d.pin?' '+d.pin:'')},
{id:'us-case',cat:'foreign',name:'US case',rule:'25.1',k:'case',sec:'B',
 tip:'The case name is followed by a comma. Put the court and year in brackets at the end. Leave the court out for US Supreme Court cases reported in the US series.',
 f:[S('mode','Status',[['rep','Reported'],['unrep','Unreported (slip opinion)']],{w:2}),T('name','Case name',{w:2,req:1,clean:'case',ph:'Hollis v Stratos Launch Corp'}),T('vol','Volume',{when:d=>d.mode==='rep',req:1}),T('series','Report series',{when:d=>d.mode==='rep',req:1,ph:'F 4th'}),T('page','Starting page',{when:d=>d.mode==='rep',req:1}),T('court','Court',{ph:'9th Cir',help:'Omit for the US Supreme Court in “US”.'}),T('year','Year',{when:d=>d.mode==='rep',req:1}),T('docket','Docket number',{when:d=>d.mode==='unrep',req:1,ph:'No 23-1184'}),DATE('date','Full date',{when:d=>d.mode==='unrep',req:1}),PIN('1127'),T('jj','Judge',{pin:1})],
 ex:{mode:'rep',name:'Hollis v Stratos Launch Corp',vol:'98',series:'F 4th',page:'1120',court:'9th Cir',year:'2024',pin:'1127'},
 cite:d=>{const jj=d.pin&&d.jj?` (${d.jj})`:'';if(d.mode==='unrep')return `${I(d.name)} (${J(d.court,d.docket,d.date)})`+(d.pin?' slip op '+d.pin:'')+jj;return `${I(d.name)}, ${SP(d.vol,d.series,d.page)}`+(d.pin?', '+d.pin:'')+jj+` (${J(d.court,d.year)})`;}},
{id:'us-code',cat:'foreign',name:'US Code provision',rule:'25.2',k:'leg',sec:'C',
 tip:'The title number goes before the code abbreviation. Use § for one section and §§ for several. The statute’s name and its original section are optional.',
 f:[T('title','Statute name (optional)',{w:2}),T('orig','Original section (optional)',{ph:'§ 102'}),T('tno','Code title number',{req:1,ph:'51'}),T('code','Code',{req:1,ph:'USC'}),T('sec','Section(s)',{req:1,ph:'§ 51303',nodash:1}),T('year','Year of code',{req:1,ph:'2018'})],
 ex:{title:'',tno:'51',code:'USC',sec:'§ 51303',year:'2018'},
 cite:d=>(d.title?I(d.title)+(d.orig?' '+d.orig:'')+', ':'')+`${d.tno} ${d.code} ${d.sec} (${d.year})`,sort:d=>d.title||d.code,
 txt:d=>({first:d.title?I(d.title):`${d.tno} ${d.code} ${d.sec}`,later:d.st?I(d.st):(d.title?I(d.title):`${d.code} ${d.sec}`)}),subHead:d=>d.st?I(d.st):(d.title?I(d.title):`${d.tno} ${d.code} ${d.sec}`)},
{id:'us-const',cat:'foreign',name:'US Constitution',rule:'25.4',k:'leg',sec:'C',st:false,
 tip:'Pinpoint to the article, section (§) and clause, or to the amendment.',
 f:[T('which','Constitution',{w:2,req:1,ph:'United States Constitution'}),PIN('art I § 8 cl 3','',{nodash:1,w:2})],
 ex:{which:'United States Constitution',pin:'art I § 8 cl 3'},
 cite:d=>SP(I(d.which),d.pin),txt:d=>({first:'the '+I(d.which),later:'the '+I(d.which)}),subHead:d=>I(d.which)},
{id:'ca-stat',cat:'foreign',name:'Canadian statute',rule:'15.2',k:'leg',sec:'C',
 tip:'Give the statute volume (RSC, SC, RSO…), then the year, any supplement, and the chapter, with commas between them.',
 f:[T('title','Title',{w:2,req:1,ph:'Criminal Code'}),T('vol','Statute volume',{req:1,ph:'RSC'}),T('year','Year',{req:1,ph:'1985'}),T('supp','Supplement / session',{ph:'1st Supp'}),T('chap','Chapter',{req:1,ph:'C-46',nodash:1}),PIN('s 342.1','',{nodash:1})],
 ex:{title:'Criminal Code',vol:'RSC',year:'1985',chap:'C-46',pin:'s 342.1'},
 cite:d=>`${I(d.title)}, ${d.vol} ${d.year}${d.supp?` (${d.supp})`:''}, c ${d.chap}`+(d.pin?', '+d.pin:''),txt:d=>({first:I(d.title),later:d.st?I(d.st):I(d.title)})}
];
const TMAP=Object.fromEntries(TYPES.map(t=>[t.id,t]));
